### PR TITLE
add new logos

### PR DESCRIPTION
**Pull request by tarjelavik**

### CODE REVIEW

**Comment by tarjelavik** [comment]
@Caroline-A, do you think there will be more changes to the logo? And should the english site use one line or two line logo?

**Comment by Caroline-A** [comment]
> @Caroline-A, do you think there will be more changes to the logo? And should the english site use one line or two line logo?

Yep there is going to be a small change to the Norwegian one so if we can keep this on-hold for now that is good. I can let you know when we have the new versions. 

English will probably be the one line one (as I guess this matches the size of the Norwegian one best?)

If you have anything like technical issues with the svg that should be passed on to the graphics person perhaps you could write them here and then @hmbjerkan can pass them on at the same time as our feedback? Current feedback is cosmetic: "den norske undertekst I den norske logo skal justeres litt vertikalt (for mye mellomrom mellom "finn bærekraftsforskning" og undertekst, og undertekst ligger litt for lavt ift den vertikale linjen) - se nettsiden".

**Comment by tarjelavik** [comment]
Agree on the spacing. No other comments.

**Comment by Caroline-A** [comment]
@tarjelavik On main we are currently using the 2-line version in Norwegian and the 1-line version in English, here you have used 2-line for both. I think for English, the 1-line one looks better... less white space... if it's not much work to swap out the file? :)

**Review by tarjelavik — COMMENTED** [review]
Nope, update is building

**Review by Caroline-A — APPROVED** [review]
Perfect!

**Pull request merged**
